version: "3.9"

# rebuild: docker-compose build --no-cache app
# start: docker-compose up -d app
# shutdown: docker-compose down app
# reattach: docker attach tsar --detach-keys="ctrl-c"
# shell in running container: docker exec -it tsar /bin/bash

# debug in ipython
# toggle python, bash commands below
# `docker-compose run --rm app`

services:
  app:
    environment:
      - APP_PATH=/tsar
      - PYTHONPATH=/tsar
      - HOST_USER=${USER}
      - HOST_DIR=.
      - HOST_HOME=${HOME}
      - SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
      - PYTHONBREAKPOINT=ipdb.set_trace
    container_name: tsar
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8137:8137" # tsar cli client
      - "8138:8138" # es
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - ${HOME}:${HOME}
      - .:/tsar
      - ./resources/dev_config/.bash_history:/root/.bash_history
      - ./resources/dev_config/.inputrc:/root/.inputrc
      - ./resources/dev_config/.ipython:/root/.ipython

    command: service elasticsearch start

    # command: /bin/bash
    command: python "/tsar/tsar/app/app.py"
