version: "3.9"

# rebuild: docker-compose build --no-cache app

# DEBUG:
# `command: /bin/bash` -> only command to run.
# `docker compose up -d`
# `docker exec -it tsar /bin/bash` # get shell in container
# `service elasticsearch start`: doesn't get killed on app restart
# `python tsar/tsar/app/app.py` starts fast; ctrl-c once to get server shell to debug cli.

services:
  app:
    environment:
      - APP_PATH=/tsar
      - PYTHONPATH=/tsar
      - HOST_USER=${USER}
      - HOST_DIR=.
      - HOST_HOME=${HOME}
      - SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
      - PYTHONBREAKPOINT=ipdb.set_trace
    container_name: tsar
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8137:8137" # tsar cli client
      - "8138:8138" # es
      - "8139:8139" # file server
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - .:/tsar
      - ./resources/dev_config/.bash_history:/root/.bash_history
      - ./resources/dev_config/.inputrc:/root/.inputrc
      - ./resources/dev_config/.ipython:/root/.ipython

    command: service elasticsearch start
    command: python "/tsar/tsar/app/app.py"

    # command: /bin/bash
