# parsed omni_record.py
OMNI_PARSED_OMNI_RECORD = {'record_id': '/Users/trensink/git/my_repos/tsar/tests/fixtures/omni_doc.md',
 'record_type': 'omni',
 'record_name': '/Users/trensink/git/my_repos/tsar/tests/fixtures/omni_doc.md',
 'record_summary': 'Test doc for omni record parsing.\n\n# Markdown-formatted links\n\n- [link to arxiv source doc](https://arxiv.org/abs/1906.03926)\n- [random wikipedia article](https://en.wikipedia.org/wiki/Le_Jour_des_fourmis)\n- [relative link to wiki doc](./wiki_docs/doc1.md)\n\n# Bare links\n\n- bare filepath: ./wiki_docs/doc1.md for info\n- bare link: https://arxiv.org/abs/1906.03925\n\n# Invalid links\n\n- this/is/not/a/valid/path\n- htp://invalid_url\n',
 'utc_last_access': 1600681343.0,
 'content': 'Test doc for omni record parsing.\n\n# Markdown-formatted links\n\n- [link to arxiv source doc](https://arxiv.org/abs/1906.03926)\n- [random wikipedia article](https://en.wikipedia.org/wiki/Le_Jour_des_fourmis)\n- [relative link to wiki doc](./wiki_docs/doc1.md)\n\n# Bare links\n\n- bare filepath: ./wiki_docs/doc1.md for info\n- bare link: https://arxiv.org/abs/1906.03925\n\n# Invalid links\n\n- this/is/not/a/valid/path\n- htp://invalid_url\n',
 'access_times': [1600681343.0],
 'links': {'/Users/trensink/git/my_repos/tsar/tests/fixtures/wiki_docs/doc1.md': "# main bit\n\nI'm interested in information organization.  I think thiss app can help!\n\n\n# caveats\n\nIt's clear that there is interest in this domain, but unclear how much exists.",
  'https://arxiv.org/abs/1906.03926': 'To be successful in real-world tasks, Reinforcement Learning (RL) needs to\nexploit the compositional, relational, and hierarchical structure of the world,\nand learn to transfer it to the task at hand. Recent advances in representation\nlearning for language make it possible to build models that acquire world\nknowledge from text corpora and integrate this knowledge into downstream\ndecision making problems. We thus argue that the time is right to investigate a\ntight integration of natural language understanding into RL in particular. We\nsurvey the state of the field, including work on instruction following, text\ngames, and learning from textual domain knowledge. Finally, we call for the\ndevelopment of new environments as well as further investigation into the\npotential uses of recent Natural Language Processing (NLP) techniques for such\ntasks.',
  'https://en.wikipedia.org/wiki/Le_Jour_des_fourmis': ''},
 'keywords': ['the',
  'learning',
  'language',
  'links',
  'bare',
  'for',
  'to',
  'knowledge']}

OMNI_PARSED_SOURCE_DOC1 = {'record_id': '/Users/trensink/git/my_repos/tsar/tests/fixtures/source_path1/source1_doc.md',
 'record_type': 'omni',
 'record_name': '/Users/trensink/git/my_repos/tsar/tests/fixtures/source_path1/source1_doc.md',
 'record_summary': "This is the 'source1' markdown file with some content for parsing/testing.\n\n# links\nbare links\n- ../source_path2/source2_doc.md\n- https://arxiv.org/abs/1906.03926\n\nequivalentmarkdown-style links\n\n- [rel link to source2](../source_path2/source2_doc.md)\n- [external link](https://arxiv.org/abs/1906.03926)\n\n# Formatting\n\nlist:\n- get milk\n- *dont* get soda\n- get eggs\n\n**bold item**\n*italic item*\n\n## subheading\nsubheading text\n### subsubheading\nsubsubheading text\n",
 'utc_last_access': 1600706371.0,
 'content': "This is the 'source1' markdown file with some content for parsing/testing.\n\n# links\nbare links\n- ../source_path2/source2_doc.md\n- https://arxiv.org/abs/1906.03926\n\nequivalentmarkdown-style links\n\n- [rel link to source2](../source_path2/source2_doc.md)\n- [external link](https://arxiv.org/abs/1906.03926)\n\n# Formatting\n\nlist:\n- get milk\n- *dont* get soda\n- get eggs\n\n**bold item**\n*italic item*\n\n## subheading\nsubheading text\n### subsubheading\nsubsubheading text\n",
 'access_times': [1600706371.0],
 'links': {'/Users/trensink/git/my_repos/tsar/tests/fixtures/source_path2/source2_doc.md': "# main bit\n\nI'm interested in information organization.  I think thiss app can help!\n\n\n# caveats\n\nIt's clear that there is interest in this domain, but unclear how much exists.",
  'https://arxiv.org/abs/1906.03926': 'To be successful in real-world tasks, Reinforcement Learning (RL) needs to\nexploit the compositional, relational, and hierarchical structure of the world,\nand learn to transfer it to the task at hand. Recent advances in representation\nlearning for language make it possible to build models that acquire world\nknowledge from text corpora and integrate this knowledge into downstream\ndecision making problems. We thus argue that the time is right to investigate a\ntight integration of natural language understanding into RL in particular. We\nsurvey the state of the field, including work on instruction following, text\ngames, and learning from textual domain knowledge. Finally, we call for the\ndevelopment of new environments as well as further investigation into the\npotential uses of recent Natural Language Processing (NLP) techniques for such\ntasks.'},
 'keywords': ['subsubheading',
  'subheading',
  'the',
  'learning',
  'language',
  'links',
  'text',
  'knowledge']}

OMNI_PARSED_SOURCE_DOC2 = {'record_id': '/Users/trensink/git/my_repos/tsar/tests/fixtures/source_path2/source2_doc.md',
 'record_type': 'omni',
 'record_name': '/Users/trensink/git/my_repos/tsar/tests/fixtures/source_path2/source2_doc.md',
 'record_summary': "# main bit\n\nI'm interested in information organization.  I think thiss app can help!\n\n\n# caveats\n\nIt's clear that there is interest in this domain, but unclear how much exists.",
 'utc_last_access': 1600681342.0,
 'content': "# main bit\n\nI'm interested in information organization.  I think thiss app can help!\n\n\n# caveats\n\nIt's clear that there is interest in this domain, but unclear how much exists.",
 'access_times': [1600681342.0],
 'links': {},
 'keywords': ['information',
  'interested',
  'interest',
  'unclear',
  'caveats',
  'clear',
  'thiss',
  'think']}
  