version: 2.1
jobs:
  build:
      docker:
        - image: cimg/base:2020.01
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: docker build -t docker.io/tcrensink/tsar:latest .
        - run:
            command: echo "stuff: $(ls -la)"
#   workflows:
#     version: 2
#     build-master:
#       jobs:
#         - build:
#             filters:
#               branches:
#                 only: master
