version: 2.1
jobs:
  build:
    docker:
      - image: docker.io/tcrensink/tsar
    steps:
      - checkout
      - run:
          name: info
          command: |
            echo "user:" $(whoami)
            echo "current dir:" $(pwd)
            echo "current dir contents:" $(ls -al)
      - run:
          name: setup environemnt
          command: |
            export HOST_DIR="$(pwd)"
            export PYTHONPATH="$PYTHONPATH:$(pwd)"
      - run:
          name: run tests
          command: |
            pytest tests
