version: 2.1
jobs:
  build:
      docker:
        - image: cimg/base:2020.01
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: docker build -t tcrensink/tsar:latest .
  workflows:
    version: 2
    build-master:
      jobs:
        - build:
            filters:
              branches:
                only: master
