version: 2.1
jobs:
  build:
      docker:
        - image: cimg/base:2020.01
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: build custom image
            command: docker build -t docker.io/tcrensink/tsar:latest .
        - run:
            name: info
            command: |
              echo "user:" $(whoami)
              echo "current dir:" $(pwd)
              echo "current dir contents:" $(ls -al)
#   workflows:
#     version: 2
#     build-master:
#       jobs:
#         - build:
#             filters:
#               branches:
#                 only: master
