version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: run container
          command: |
            make tsar_shell
            echo "user:" $(whoami)
            echo "current dir:" $(pwd)
      - run:
          name: see code
          command: |
            ls -al
            echo '^^ see code above ^^'
