version: 2.1
jobs:
  build:
    docker:
      - image: docker.io/tcrensink/tsar
    steps:
      - checkout
      - run:
          name: 1) container info
          command: |
            echo "user:" $(whoami)
            echo "current dir:" $(pwd)
            echo "current dir contents:" $(ls -al)
      - run:
          name: see code
          command: |
            export PYTHONPATH="$PYTHONPATH:$(pwd)"
            echo "$PYTHONPATH"
