version: 0.1
jobs:
  build:
    docker:
      - image: docker.io/tcrensink/tsar
    steps:
      - checkout
      - run:
          name: environemnt setup
          command: |
            export HOST_DIR="$(pwd)"
            export PYTHONPATH="$(pwd)"
      - run:
          name: info
          command: |
            echo "user:" $(whoami)
            echo "current dir:" $(pwd)
            echo "current dir contents:" $(ls -al)
            echo "python path: $PYTHONPATH"
            echo "HOST_DIR env var: $HOST_DIR"
      - run:
          name: run tests
          command: |
            echo "$PYTHONPATH"
            pytest tests/tsar/test_passthrough.py
