version: 2.1
jobs:
  build:
    docker:
      - image: docker.io/tcrensink/tsar
    steps:
      - checkout
      - run:
          name: 1) run container
          command: |
            echo "user:" $(whoami)
            echo "current dir:" $(pwd)
      - run:
          name: see code
          command: |
            ls -al
            echo '^^ see code above ^^'
      - run:
          name: run tests
          command: |
            pytest tests
